---
title: "ME810 - Áreas Contaminadas"
output:
  html_document: default
---

```{r, echo=FALSE, warning=FALSE}
library(readxl) #biblioteca para ler o excel
library(knitr)
library(ggplot2)

data <- read_excel("C:/Users/Melissa Palermo/Documents/GitHub/Areas-Contaminadas---ME810/BASE.xlsx") #leitura dos dados

dados<-data.frame(data)

dados1<-dados

dados1$id=0

tabela<-matrix(0,832,3)
n=1
i=0
j=0


for (i in 1:832){
   aux = 0
   for (j in 1:n){
       if (dados1[i, 7] == tabela[j, 2]){
           if (dados1[i, 8] == tabela[j, 3]){
                 dados1[i, 1] = tabela[j, 1]
                 aux = 1;
           }
       }
   }
      if (aux == 0) {
          tabela[n, 2] = dados1[i, 7]
          tabela[n, 3] = dados1[i, 8]
          dados1[i, 1] = n
          tabela[j,1]=n
          n=n+1
      }
   }

#esses 2 comandos criam um arquivo em csv já pronto, pra nao ter que ficar rodando o excel sempre

write.csv(dados1,file="teste.csv")
dados<- read.csv2("C:/Users/Melissa Palermo/Documents/GitHub/Areas-Contaminadas---ME810/teste.csv",sep=",")

n2011 = length(which(dados$ano==2011))
n2012 = length(which(dados$ano==2012))
n2013 = length(which(dados$ano==2013))
n2014 = length(which(dados$ano==2014))
n2015 = length(which(dados$ano==2015))
n2016 = length(which(dados$ano==2016))

y= c(n2011, n2012, n2013, n2014, n2015, n2016)
x=c(2011, 2012, 2013, 2014, 2015, 2016)

plot(x, y, xlab = "Ano", ylab="Númedo de áreas contaminadas" )

plot(dados$atividade, xlab="Atividade", ylab="Número de áreas contaminadas")

summary(dados$bairro) #número de areas contaminadas em cada bairro
str(dados$bairro) #para saber a quantidde de bairros => 99 bairros

maxbairros =  c("Barão GeraldoO","Boa Vista", "Bonfim", "Cambuí", "Centro", "Distrito Industrial", "Jd. Chapadão", "Taquaral", "Vila Industrial") #BAIRROS COM MAIS DE 15 AREAS

maybairros =  c(length(which(dados$bairro=="BARÃO GERALDO")),length(which(dados$bairro=="BOA VISTA")),length( which(dados$bairro=="BONFIM")), length(which(dados$bairro=="CAMBUI")), length(which(dados$bairro=="CENTRO")), length(which(dados$bairro=="DISTRITO INDUSTRIAL")), length(which(dados$bairro=="JARDIM CHAPADÃO")),length( which(dados$bairro=="TAQUARAL")), length(which(dados$bairro=="VILA INDUSTRIAL"))) 

fator = as.factor(maxbairros)
plot(fator, maybairros) 
```



```{r, echo=FALSE}

```
